{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "86a6165f-dc4f-45fc-9ea3-e1d9fca3e64b",
   "metadata": {},
   "source": [
    "# Automatic segmentation of precipitate statistics using Mask RCNN architecture\n",
    "\n",
    "This code utilizes a Mask R-CNN deep learning architecture to automatically extract precipitate statistics from transmission electron microscopy (TEM) images. \n",
    "The code is developed as part of a master's thesis in applied physics, the code segments precipitates within the images, enabling the automatic measurement of precipitate length and cross-sections. \n",
    "By automating this process, it significantly accelerates the analysis of precipitate distributions, aiding in materials research and development.\n",
    "\n",
    "## Author:\n",
    "\n",
    "**Espen J. Gregory** - Developed for Master thesis in Physics 2024\n",
    "\n",
    "## Note:\n",
    "\n",
    "- It is recommended to have a GPU and the CUDA-version of Pytorch installed (However it is not required).\n",
    "- Make sure model files (.pth) are placed in the same folder as the notebook\n",
    "- Data can be loaded in two ways, either by directly uploading the .DM3 file, or converting the .DM3 to an image (.jpeg/.png) and manually selecting the calibration unit *nm_per_px*.\n",
    "- Mask R-CNN documentation: https://arxiv.org/abs/1703.06870"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8effdb76-bd47-4b51-9b79-b7e3fdc6a06d",
   "metadata": {},
   "source": [
    "### Imports/Dependencies and Pytorch initalization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "7f4313ae-2b43-4c52-b858-ff8be91af44b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of torchvision._meta_registrations failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\torchvision\\_meta_registrations.py\", line 26, in <module>\n",
      "    def meta_roi_align(input, rois, spatial_scale, pooled_height, pooled_width, sampling_ratio, aligned):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\torchvision\\_meta_registrations.py\", line 19, in wrapper\n",
      "    get_meta_lib().impl(getattr(getattr(torch.ops.torchvision, op_name), overload_name), fn)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\library.py\", line 234, in impl\n",
      "    raise RuntimeError(\"This is not allowed since there's already a kernel registered from python overriding {}\"\n",
      "RuntimeError: This is not allowed since there's already a kernel registered from python overriding roi_align's behavior for Meta dispatch key and torchvision namespace.\n",
      "]\n",
      "[autoreload of torchvision._utils failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to StrEnumMeta object\n",
      "]\n",
      "[autoreload of sympy.core.parameters failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to _global_parameters object\n",
      "]\n",
      "[autoreload of sympy.core.kind failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to KindMeta object\n",
      "]\n",
      "[autoreload of sympy.core.singleton failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to Singleton object\n",
      "]\n",
      "[autoreload of sympy.core.add failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\add.py\", line 86, in <module>\n",
      "    class Add(Expr, AssocOp):\n",
      "TypeError: multiple bases have instance lay-out conflict\n",
      "]\n",
      "[autoreload of sympy.logic.boolalg failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\logic\\boolalg.py\", line 455, in <module>\n",
      "    class BooleanFunction(Application, Boolean):\n",
      "TypeError: multiple bases have instance lay-out conflict\n",
      "]\n",
      "[autoreload of sympy.core.symbol failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'Dummy' object layout differs from 'Dummy'\n",
      "]\n",
      "[autoreload of sympy.core.function failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\function.py\", line 380, in <module>\n",
      "    class Function(Application, Expr):\n",
      "TypeError: multiple bases have instance lay-out conflict\n",
      "]\n",
      "[autoreload of sympy.core.numbers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\numbers.py\", line 2740, in <module>\n",
      "    class Zero(IntegerConstant, metaclass=Singleton):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 166, in __init__\n",
      "    cls._instance = obj = Basic.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Zero' object\n",
      "]\n",
      "[autoreload of sympy.core.mul failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\mul.py\", line 91, in <module>\n",
      "    class Mul(Expr, AssocOp):\n",
      "TypeError: multiple bases have instance lay-out conflict\n",
      "]\n",
      "[autoreload of sympy.core.exprtools failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\exprtools.py\", line 25, in <module>\n",
      "    _eps = Dummy(positive=True)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.core failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\__init__.py\", line 37, in <module>\n",
      "    Catalan = S.Catalan\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Catalan' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.assumptions.assume failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to PredicateMeta object\n",
      "]\n",
      "[autoreload of sympy.polys.polyoptions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to OptionType object\n",
      "]\n",
      "[autoreload of sympy.polys.domains.gaussiandomains failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'GaussianInteger' object layout differs from 'GaussianInteger'\n",
      "]\n",
      "[autoreload of sympy.polys.domains.expressiondomain failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\domains\\expressiondomain.py\", line 16, in <module>\n",
      "    class ExpressionDomain(Field, CharacteristicZero, SimpleDomain):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\domains\\expressiondomain.py\", line 155, in ExpressionDomain\n",
      "    zero = Expression(0)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\domains\\expressiondomain.py\", line 28, in __init__\n",
      "    self.ex = sympify(ex)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sympify.py\", line 396, in sympify\n",
      "    return conv(a)\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.polys.domains.expressionrawdomain failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\domains\\expressionrawdomain.py\", line 13, in <module>\n",
      "    class ExpressionRawDomain(Field, CharacteristicZero, SimpleDomain):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\domains\\expressionrawdomain.py\", line 20, in ExpressionRawDomain\n",
      "    zero = S.Zero\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.elementary.miscellaneous failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\miscellaneous.py\", line 35, in <module>\n",
      "    class IdentityFunction(Lambda, metaclass=Singleton):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\miscellaneous.py\", line 49, in IdentityFunction\n",
      "    _symbol = Dummy('x')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.functions.elementary.piecewise failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\piecewise.py\", line 16, in <module>\n",
      "    Undefined = S.NaN  # Piecewise()\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'NaN' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.elementary.exponential failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\exponential.py\", line 36, in <module>\n",
      "    class ExpBase(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\exponential.py\", line 39, in ExpBase\n",
      "    _singularities = (S.ComplexInfinity,)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'ComplexInfinity' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.combinatorial.numbers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\combinatorial\\numbers.py\", line 49, in <module>\n",
      "    _sym = Symbol('x')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 381, in __xnew_cached_\n",
      "    return Symbol.__xnew__(cls, name, **assumptions)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.functions.elementary.trigonometric failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\trigonometric.py\", line 45, in <module>\n",
      "    class TrigonometricFunction(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\elementary\\trigonometric.py\", line 49, in TrigonometricFunction\n",
      "    _singularities = (S.ComplexInfinity,)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'ComplexInfinity' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.error_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\error_functions.py\", line 1809, in <module>\n",
      "    class Si(TrigonometricIntegral):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\error_functions.py\", line 1881, in Si\n",
      "    _atzero = S.Zero\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.zeta_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\zeta_functions.py\", line 394, in <module>\n",
      "    class zeta(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\function.py\", line 184, in __init__\n",
      "    nargs = tuple(ordered(set(nargs)))\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.gamma_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\gamma_functions.py\", line 34, in <module>\n",
      "    class gamma(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\gamma_functions.py\", line 112, in gamma\n",
      "    _singularities = (S.ComplexInfinity,)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'ComplexInfinity' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.tensor_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\tensor_functions.py\", line 90, in <module>\n",
      "    class KroneckerDelta(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\function.py\", line 184, in __init__\n",
      "    nargs = tuple(ordered(set(nargs)))\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Integer' object\n",
      "]\n",
      "[autoreload of sympy.polys.polyquinticconst failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\polyquinticconst.py\", line 20, in <module>\n",
      "    x = Symbol('x')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 381, in __xnew_cached_\n",
      "    return Symbol.__xnew__(cls, name, **assumptions)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.polys.polyroots failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\polyroots.py\", line 34, in <module>\n",
      "    z = Symbol('z')  # importing from abc cause O to be lost as clashing symbol\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 381, in __xnew_cached_\n",
      "    return Symbol.__xnew__(cls, name, **assumptions)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.functions.special.delta_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\delta_functions.py\", line 17, in <module>\n",
      "    class DiracDelta(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\delta_functions.py\", line 152, in DiracDelta\n",
      "    def eval(cls, arg, k=S.Zero):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.sets.sets failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'EmptySet' object layout differs from 'EmptySet'\n",
      "]\n",
      "[autoreload of sympy.sets.fancysets failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\fancysets.py\", line 24, in <module>\n",
      "    class Rationals(Set, metaclass=Singleton):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\fancysets.py\", line 41, in Rationals\n",
      "    _inf = S.NegativeInfinity\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'NegativeInfinity' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.sets.conditionset failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\conditionset.py\", line 16, in <module>\n",
      "    adummy = Dummy('conditionset')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.sets.ordinals failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\ordinals.py\", line 281, in <module>\n",
      "    ord0 = OrdinalZero()\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\ordinals.py\", line 82, in __new__\n",
      "    obj = super().__new__(cls, *terms)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'OrdinalZero' object\n",
      "]\n",
      "[autoreload of sympy.sets failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\sets\\__init__.py\", line 12, in <module>\n",
      "    Complexes = S.Complexes\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Complexes' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.bessel failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\bessel.py\", line 106, in <module>\n",
      "    class besselj(BesselBase):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\bessel.py\", line 175, in besselj\n",
      "    _a = S.One\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.polynomials failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\polynomials.py\", line 25, in <module>\n",
      "    _x = Dummy('x')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.functions.special.spherical_harmonics failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\spherical_harmonics.py\", line 13, in <module>\n",
      "    _x = Dummy(\"x\")\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.functions.special.elliptic_integrals failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\elliptic_integrals.py\", line 188, in <module>\n",
      "    class elliptic_e(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\function.py\", line 184, in __init__\n",
      "    nargs = tuple(ordered(set(nargs)))\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.functions.special.beta_functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\functions\\special\\beta_functions.py\", line 20, in <module>\n",
      "    class beta(Function):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\function.py\", line 184, in __init__\n",
      "    nargs = tuple(ordered(set(nargs)))\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\sorting.py\", line 312, in ordered\n",
      "    yield from value\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.printing.smtlib failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\printing\\smtlib.py\", line 25, in <module>\n",
      "    class SMTLibPrinter(Printer):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\printing\\smtlib.py\", line 50, in SMTLibPrinter\n",
      "    EqualityPredicate(): '=',\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\assumptions\\assume.py\", line 308, in __new__\n",
      "    obj = super().__new__(cls, *args)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'EqualityPredicate' object\n",
      "]\n",
      "[autoreload of sympy.printing.maple failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\printing\\maple.py\", line 67, in <module>\n",
      "    S.Pi: 'Pi',\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Pi' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.polys.polyfuncs failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\polyfuncs.py\", line 208, in <module>\n",
      "    def rational_interpolate(data, degnum, X=symbols('x')):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 798, in symbols\n",
      "    symbol = cls(literal(name), **args)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.matrices.utilities failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to DotProdSimpState object\n",
      "]\n",
      "[autoreload of sympy.tensor.indexed failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\tensor\\indexed.py\", line 362, in <module>\n",
      "    class IndexedBase(Expr, NotIterable):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\tensor\\indexed.py\", line 440, in IndexedBase\n",
      "    def __new__(cls, label, shape=None, *, offset=S.Zero, strides=None, **kw_args):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.polys.matrices.eigen failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\polys\\matrices\\eigen.py\", line 17, in <module>\n",
      "    def dom_eigenvects(A, l=Dummy('lambda')):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.matrices.matrixbase failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\matrixbase.py\", line 98, in <module>\n",
      "    class MatrixBase(Printable):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\matrixbase.py\", line 110, in MatrixBase\n",
      "    zero = S.Zero\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.matrices.expressions.inverse failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\inverse.py\", line 8, in <module>\n",
      "    class Inverse(MatPow):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\inverse.py\", line 33, in Inverse\n",
      "    exp = S.NegativeOne\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'NegativeOne' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.matrices.expressions.permutation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\permutation.py\", line 168, in <module>\n",
      "    class MatrixPermute(MatrixExpr):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\permutation.py\", line 220, in MatrixPermute\n",
      "    def __new__(cls, mat, perm, axis=S.Zero):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.matrices.expressions.matmul failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matmul.py\", line 24, in <module>\n",
      "    class MatMul(MatrixExpr, Mul):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matmul.py\", line 40, in MatMul\n",
      "    identity = GenericIdentity()\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\special.py\", line 184, in __new__\n",
      "    return super(Identity, cls).__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matexpr.py\", line 83, in __new__\n",
      "    return Basic.__new__(cls, *args, **kwargs)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'GenericIdentity' object\n",
      "]\n",
      "[autoreload of sympy.matrices.expressions.matadd failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matadd.py\", line 19, in <module>\n",
      "    class MatAdd(MatrixExpr, Add):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matadd.py\", line 36, in MatAdd\n",
      "    identity = GenericZeroMatrix()\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\special.py\", line 78, in __new__\n",
      "    return super(ZeroMatrix, cls).__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matexpr.py\", line 83, in __new__\n",
      "    return Basic.__new__(cls, *args, **kwargs)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'GenericZeroMatrix' object\n",
      "]\n",
      "[autoreload of sympy.matrices.expressions.matexpr failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matexpr.py\", line 739, in <module>\n",
      "    class _LeftRightArgs:\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\matrices\\expressions\\matexpr.py\", line 753, in _LeftRightArgs\n",
      "    def __init__(self, lines, higher=S.One):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.calculus.singularities failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\calculus\\singularities.py\", line 120, in <module>\n",
      "    def monotonicity_helper(expression, predicate, interval=S.Reals, symbol=None):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Reals' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.calculus.finite_diff failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\calculus\\finite_diff.py\", line 29, in <module>\n",
      "    def finite_diff_weights(order, x_list, x0=S.One):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'One' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.calculus.util failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\calculus\\util.py\", line 689, in <module>\n",
      "    def is_convex(f, *syms, domain=S.Reals):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Reals' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.series.approximants failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\series\\approximants.py\", line 7, in <module>\n",
      "    def approximants(l, X=Symbol('x'), simplify=False):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 381, in __xnew_cached_\n",
      "    return Symbol.__xnew__(cls, name, **assumptions)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.series.sequences failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 365, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 323, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'EmptySequence' object layout differs from 'EmptySequence'\n",
      "]\n",
      "[autoreload of sympy.integrals.meijerint failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\meijerint.py\", line 76, in <module>\n",
      "    z = Dummy('z')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.integrals.trigonometry failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\trigonometry.py\", line 26, in <module>\n",
      "    _u = Dummy('u')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.integrals.laplace failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\laplace.py\", line 2199, in <module>\n",
      "    class InverseLaplaceTransform(IntegralTransform):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\laplace.py\", line 2210, in InverseLaplaceTransform\n",
      "    _none_sentinel = Dummy('None')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.integrals.transforms failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\transforms.py\", line 821, in <module>\n",
      "    class InverseMellinTransform(IntegralTransform):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\integrals\\transforms.py\", line 832, in InverseMellinTransform\n",
      "    _none_sentinel = Dummy('None')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.simplify.powsimp failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\simplify\\powsimp.py\", line 610, in <module>\n",
      "    _y = Dummy('y')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.simplify.hyperexpand failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\simplify\\hyperexpand.py\", line 672, in <module>\n",
      "    _x = Dummy('x')\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\basic.py\", line 231, in __new__\n",
      "    obj._assumptions = cls.default_assumptions\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.simplify.simplify failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\simplify\\simplify.py\", line 1585, in <module>\n",
      "    def clear_coefficients(expr, rhs=S.Zero):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.solvers.solveset failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\solvers\\solveset.py\", line 112, in <module>\n",
      "    def _invert(f_x, y, x, domain=S.Complexes):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Complexes' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.solvers.diophantine.diophantine failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\solvers\\diophantine\\diophantine.py\", line 1252, in <module>\n",
      "    def diophantine(eq, param=symbols(\"t\", integer=True), syms=None,\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 798, in symbols\n",
      "    symbol = cls(literal(name), **args)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 330, in __new__\n",
      "    return Symbol.__xnew_cached_(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\cache.py\", line 72, in wrapper\n",
      "    retval = cfunc(*args, **kwargs)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Symbol' object\n",
      "]\n",
      "[autoreload of sympy.solvers.ode.nonhomogeneous failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\solvers\\ode\\nonhomogeneous.py\", line 278, in <module>\n",
      "    def _undetermined_coefficients_match(expr, x, func=None, eq_homogeneous=S.Zero):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Zero' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.solvers.inequalities failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\solvers\\inequalities.py\", line 383, in <module>\n",
      "    def solve_univariate_inequality(expr, gen, relational=True, domain=S.Reals, continuous=False):\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Reals' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.solvers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\solvers\\__init__.py\", line 42, in <module>\n",
      "    Complexes = S.Complexes\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\singleton.py\", line 118, in __getattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: Attribute 'Complexes' was not installed on SymPy registry S\n",
      "]\n",
      "[autoreload of sympy.geometry.entity failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\entity.py\", line 67, in <module>\n",
      "    x, y = [Dummy('entity_dummy') for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\entity.py\", line 67, in <listcomp>\n",
      "    x, y = [Dummy('entity_dummy') for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.geometry.line failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\line.py\", line 47, in <module>\n",
      "    t, u = [Dummy('line_dummy') for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\line.py\", line 47, in <listcomp>\n",
      "    t, u = [Dummy('line_dummy') for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.geometry.plane failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\plane.py\", line 27, in <module>\n",
      "    x, y, z, t = [Dummy('plane_dummy') for i in range(4)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\plane.py\", line 27, in <listcomp>\n",
      "    x, y, z, t = [Dummy('plane_dummy') for i in range(4)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.geometry.polygon failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\polygon.py\", line 25, in <module>\n",
      "    x, y, T = [Dummy('polygon_dummy', real=True) for i in range(3)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\polygon.py\", line 25, in <listcomp>\n",
      "    x, y, T = [Dummy('polygon_dummy', real=True) for i in range(3)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n",
      "[autoreload of sympy.geometry.ellipse failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\ellipse.py\", line 37, in <module>\n",
      "    x, y = [Dummy('ellipse_dummy', real=True) for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\geometry\\ellipse.py\", line 37, in <listcomp>\n",
      "    x, y = [Dummy('ellipse_dummy', real=True) for i in range(2)]\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 492, in __new__\n",
      "    obj = Symbol.__xnew__(cls, name, **assumptions)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\sympy\\core\\symbol.py\", line 352, in __xnew__\n",
      "    obj = Expr.__new__(cls)\n",
      "TypeError: descriptor '_assumptions' for 'Basic' objects doesn't apply to a 'Dummy' object\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      "Device type: cpu\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of testMaster.DatasetEvaluator failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\krist\\AppData\\Roaming\\Python\\Python310\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"c:\\Users\\krist\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 879, in exec_module\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1017, in get_code\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 947, in source_to_code\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\krist\\Documents\\masterRepo\\src\\testMaster\\DatasetEvaluator.py\", line 472\n",
      "    \n",
      "    ^\n",
      "IndentationError: expected an indented block after 'else' statement on line 466\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "%matplotlib qt5\n",
    "import gc\n",
    "import cv2\n",
    "import time\n",
    "import torch\n",
    "import matplotlib\n",
    "import numpy as np\n",
    "import tkinter as tk\n",
    "#import _dm3_lib as dm\n",
    "import torchvision as tv\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "\n",
    "from PIL import Image\n",
    "from tkinter import filedialog\n",
    "from matplotlib.widgets import Button, Slider\n",
    "from skimage.segmentation import clear_border\n",
    "from torchvision.models.detection.faster_rcnn import FastRCNNPredictor\n",
    "from pathlib import Path\n",
    "\n",
    "\"\"\"PyTorch Initialization\"\"\"\n",
    "torch.backends.cudnn.deterministic = True\n",
    "torch.backends.cudnn.benchmark     = True\n",
    "torch.manual_seed(0)\n",
    "torch.cuda.manual_seed(0)\n",
    "device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')\n",
    "print(\"Device type: %s\"%(device))\n",
    "\n",
    "\n",
    "font = {'size'   : 18}\n",
    "matplotlib.rc('font', **font)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "b358e960",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\krist\\Documents\\masterRepo\\src\\testMaster\\DatasetEvaluator.py:151: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  self.checkpoint = torch.load(self.path, map_location=torch.device(self.device))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mask-RCNN Model Loaded\n",
      "0.3510816991329193\n",
      "Mask threshold set to 0.40\n",
      "Calibration used: 0.3511 nm/px\n",
      "Average: 10.59 nm, STDev: 13.44 nm, Number counted: 21, STDev of mean: 2.93 nm, Number density: 0.0001625nm^-2\n"
     ]
    }
   ],
   "source": [
    "# Using DataSetEvaluator\n",
    "from testMaster.DatasetEvaluator import RCNNEvaluator\n",
    "\n",
    "# If files in the dataset are .dm3 files, nm_per_px will be extracted automatically and replace the \n",
    "# existing nm_per_px value in the list. It works to have some files as dm3 and some as .jpg/.png.\n",
    "# Always give nm_per_px as a list with lenght equal to number of files to be evaluated. First value corresponds\n",
    "# to nm_per_px value for the first image and so on. For dm3 files an arbitrary value can be given, it will be replaced\n",
    "# either way.\n",
    "\n",
    "nm_per_px = [0.069661] * 1 #Cross\n",
    "#nm_per_px = [0.16685] * 6 #Length\n",
    "\n",
    "\n",
    "# Example usage:\n",
    "this_dir = Path.cwd()\n",
    "dataset_path = this_dir.parent / \"data\" / \"test_length_dm3\"\n",
    "model_path = this_dir.parent / \"data\" / \"models\" / \"cross_rcnn.pth\"\n",
    "  \n",
    "\n",
    "rcnn_evaluator = RCNNEvaluator(\n",
    "    dataset_dir = dataset_path,\n",
    "    model = model_path,\n",
    "    nm_per_px = nm_per_px,\n",
    "    cross = False,\n",
    "    device = 'cpu'\n",
    ")\n",
    "\n",
    "rcnn_evaluator.statistics()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4844296a-c466-49bb-9e2b-d4c104c13383",
   "metadata": {},
   "source": [
    "### Defining functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "97624f7a-b524-4aed-b2bd-48e970cdf481",
   "metadata": {},
   "outputs": [],
   "source": [
    "def DM_2_array(img) -> np.array:\n",
    "    \"\"\"\n",
    "    Convert Digital Micrograph file to numpy array\n",
    "\n",
    "    img: An instance of the DM3 class from _dm3_lib.py\n",
    "\n",
    "    returns a numpy array of the grayscale image\n",
    "    \"\"\"\n",
    "    nm_per_px = img.pxsize[0]\n",
    "    cons = img.contrastlimits\n",
    "    im   = img.imagedata\n",
    "    im[im>cons[1]] = cons[1]\n",
    "    im[im<cons[0]] = cons[0]\n",
    "    im =  ((im-cons[0])/(cons[1]-cons[0]))*255  #0 to 1\n",
    "    return im.astype(np.uint8), nm_per_px\n",
    "    \n",
    "def load_data() -> list:\n",
    "    \"\"\"\n",
    "    Opens dialogbox that allows selection of files\n",
    "    Returns file/files\n",
    "    \"\"\"\n",
    "    root = tk.Tk()\n",
    "    root.withdraw()\n",
    "    root.call('wm', 'attributes', '.', '-topmost', True)\n",
    "    files = filedialog.askopenfilenames(parent=root, title='Choose a file')\n",
    "    return files\n",
    "\n",
    "\n",
    "def check_image(n: int, thresh: float, erode: int) -> (np.array, np.array):\n",
    "    \"\"\"\n",
    "    Function used to check the mask overlay of image n, given a masking threshold thresh\n",
    "    \n",
    "    Returns: Image, Image with predicted mask overlay \n",
    "    \"\"\"\n",
    "    print(f\"Image checked: {model.data[n]}\")\n",
    "    pred = model.prediction[n]\n",
    "    im   = model.images[n]\n",
    "    gray    = cv2.cvtColor(im[0],cv2.COLOR_BGR2RGB)\n",
    "    overlay = gray.copy()\n",
    "    scr_thres = 0.9 #Confidence score threshold for the RPN (Region proposal network) \n",
    "    for i in range(len(pred[0]['masks'])):\n",
    "        msk=pred[0]['masks'][i,0].detach().cpu().numpy()\n",
    "        scr=pred[0]['scores'][i].detach().cpu().numpy()\n",
    "        box = [int(i) for i in pred[0]['boxes'][i].detach().cpu().numpy()]\n",
    "        if scr>scr_thres:\n",
    "\n",
    "            mask    = msk>thresh\n",
    "            kernel  = np.ones((2, 2), np.uint8) \n",
    "            mask_er = cv2.erode(mask.astype(np.float32), kernel, iterations = erode)  \n",
    "            mask    = mask_er>0\n",
    "            overlay[:,:,:][mask] =  [1,0,0] #Makes mask overlay red\n",
    "    im   = 0\n",
    "    pred = 0\n",
    "    return gray, overlay\n",
    "\n",
    "\n",
    "def update(erode, val):\n",
    "    \"\"\"\n",
    "    Function that updates the matplotlib figure when the slider is moved.\n",
    "    \"\"\"\n",
    "    global erode_it_temp, temp_threshold\n",
    "    if erode:\n",
    "        erode_it_temp = round(val)\n",
    "    else:\n",
    "        temp_threshold = val\n",
    "    gray, overlay = check_image(n, temp_threshold ,erode_it_temp)\n",
    "    ax[1].imshow(overlay)\n",
    "    fig.canvas.draw_idle()\n",
    "def Check_Mask(n, model):\n",
    "    \n",
    "    global button, thresh_slider,thresh_slider2, threshold, temp_threshold, fig, ax, erode_it, erode_it_temp\n",
    "    temp_threshold = model.threshold\n",
    "    erode_it_temp = model.erode_it\n",
    "\n",
    "    accept = False\n",
    "    fig, ax = plt.subplots(1,2,figsize = (20,10))\n",
    "    gray, overlay = check_image(n, model.threshold ,model.erode_it)\n",
    "    ax[0].imshow(gray)\n",
    "    ax[0].axis('off')\n",
    "    ax[1].imshow(overlay)\n",
    "    ax[1].axis('off')\n",
    "    axthresh  = fig.add_axes([0.125, 0.06, 0.775, 0.03])\n",
    "    axthresh2 = fig.add_axes([0.125, 0.1, 0.775, 0.03])\n",
    "    thresh_slider2 = Slider(ax=axthresh2, label='Mask threshold', valmin=0, valmax=1,valinit=model.threshold)\n",
    "    thresh_slider  = Slider(ax=axthresh, label='Erode iterations', valmin=0, valmax=10,valinit=model.erode_it,valfmt=\"%i\")\n",
    "    def accept(event):\n",
    "        model.threshold = temp_threshold\n",
    "        model.erode_it  = erode_it_temp\n",
    "        plt.close()\n",
    "    thresh_slider.on_changed(lambda x: update(True,x))\n",
    "    thresh_slider2.on_changed(lambda x: update(False,x))\n",
    "    resetax = fig.add_axes([0.8, 0.01, 0.1, 0.04])\n",
    "    button = Button(resetax, 'Accept', hovercolor='0.975')\n",
    "    button.on_clicked(accept)\n",
    "\n",
    "\n",
    "class Prediction():\n",
    "    def __init__(self,cross):\n",
    "        self.cross     = cross\n",
    "        self.size      = 1024\n",
    "        \n",
    "        \n",
    "        if self.cross:\n",
    "            self.threshold = 0.9\n",
    "            self.erode_it  = 0\n",
    "            self.PATH = r\"C:\\Users\\krist\\Documents\\masterRepo\\data\\models\\cross_rcnn.pth\"\n",
    "        else:\n",
    "            self.erode_it  = 4\n",
    "            self.threshold = 0.5\n",
    "            self.PATH = r\"C:\\Users\\krist\\Documents\\masterRepo\\data\\models\\length_rcnn.pth\"\n",
    "\n",
    "        self.checkpoint = torch.load(self.PATH, map_location=torch.device('cpu'))\n",
    "        self.model      = tv.models.detection.maskrcnn_resnet50_fpn(weights='DEFAULT', min_size=1024, max_size=2048, box_detections_per_img = 500) \n",
    "        in_features     = self.model.roi_heads.box_predictor.cls_score.in_features \n",
    "        self.model.roi_heads.box_predictor = FastRCNNPredictor(in_features,num_classes=2)\n",
    "        self.model.load_state_dict(self.checkpoint['model_state_dict'])\n",
    "        self.model.to(device)\n",
    "        self.model.eval()\n",
    "        print('Model Loaded')\n",
    "    \n",
    "    def to_tensor(self, file) -> torch.Tensor:\n",
    "        \"\"\"\n",
    "        Opens the image in grayscale, resizes it (if applicable), and converts it to a pytorch tensor\n",
    "    \n",
    "        file   (str)    : Path to file\n",
    "            \n",
    "        Returns tensor\n",
    "        \"\"\"\n",
    "        try:\n",
    "            if file.endswith('.dm3'):\n",
    "                image, nm_per_px = DM_2_array(dm.DM3(file))\n",
    "                if len(self.images) == 0:\n",
    "                    self.nm_per_px = nm_per_px\n",
    "            else:\n",
    "                image = np.array(Image.open(file).convert('L'))\n",
    "        except Exception:\n",
    "            raise ValueError(\"Something went wrong when loading the image.\")\n",
    "            pass\n",
    "        image = cv2.resize(image, dsize = (self.size,self.size))\n",
    "        image = np.expand_dims(image, axis=0)\n",
    "        \n",
    "        ## Can add filter if images are very noisy (Median recommended, gaussian makes the images too blurry)\n",
    "        # image = nd.median_filter(image, size=3) \n",
    "        image = image/np.max(image)\n",
    "        image = torch.tensor(image, dtype = torch.float32)\n",
    "        \n",
    "        return image\n",
    "\n",
    "    def evaluate(self, nm_per_px):\n",
    "        \"\"\"\n",
    "        Prediction Mask R-CNN\n",
    "\n",
    "        nm_per_px: float (Image calibration AS IF IMAGE IS 2048x2048)\n",
    "        \n",
    "        \"\"\"\n",
    "        self.data       = load_data()\n",
    "        self.nm_per_px  = nm_per_px\n",
    "        self.prediction = []\n",
    "        self.images     = []\n",
    "        self.lengths    = []\n",
    "\n",
    "        start_time = time.time()\n",
    "        for img in iter(self.data):\n",
    "            im = self.to_tensor(img).unsqueeze(0).to(device)\n",
    "            if len(self.images) == 0:\n",
    "                self.nm_per_px *=2 #Original calibration for 2048x2048, but images are resized to 1024x1024\n",
    "            with torch.no_grad(): #Predict\n",
    "                pred = self.model(im)\n",
    "                self.prediction.append(pred)\n",
    "            im = im[0].detach().cpu().numpy()\n",
    "            self.images.append(im)\n",
    "        total_time = time.time()-start_time\n",
    "        print(f\"Total interference time: {np.round(total_time,2)}s ; Time per Image: {np.round(total_time/len(self.images),3)}s\")\n",
    "    def statistics(self):\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.area    = []\n",
    "        self.lengths = []\n",
    "        print('Mask threshold set to {0:.2f}'.format(self.threshold))\n",
    "        print('Calibration used: {0:.4f} nm/px'.format(self.nm_per_px))\n",
    "        \n",
    "        if self.cross:\n",
    "            for pred in self.prediction:\n",
    "                for i in range(len(pred[0]['masks'])):\n",
    "                    box = pred[0]['boxes'][i].detach().cpu().numpy()\n",
    "                    msk = pred[0]['masks'][i,0].detach().cpu().numpy()\n",
    "                    scr = pred[0]['scores'][i].detach().cpu().numpy()\n",
    "                    mask    = msk>self.threshold\n",
    "                    kernel  = np.ones((2, 2), np.uint8) \n",
    "                    mask_er = cv2.erode(mask.astype(np.float32), kernel, iterations = self.erode_it)  \n",
    "                    msk    = mask_er>0\n",
    "                    clear = clear_border(msk)\n",
    "                    area1 = np.sum(clear)\n",
    "                    area2 = np.sum(msk)\n",
    "                    if scr>0.9 and area1 == area2:\n",
    "                        self.area.append(area1)\n",
    "            return np.array(self.area)*self.nm_per_px**2\n",
    "        else:\n",
    "            for pred in self.prediction:\n",
    "                for i in range(len(pred[0]['masks'])):\n",
    "                    scr = pred[0]['scores'][i].detach().cpu().numpy()\n",
    "                    box = pred[0]['boxes'][i].detach().cpu().numpy()\n",
    "                    msk = pred[0]['masks'][i,0].detach().cpu().numpy()\n",
    "                    mask    = msk>self.threshold\n",
    "                    kernel  = np.ones((2, 2), np.uint8) \n",
    "                    mask_er = cv2.erode(mask.astype(np.float32), kernel, iterations = self.erode_it)  \n",
    "                    msk     = clear_border(mask_er>0,buffer_size=10)\n",
    "                    if scr>0.9 and np.any(msk):\n",
    "                        rect = cv2.minAreaRect(np.argwhere((msk>self.threshold)))\n",
    "                        (center), (width,height), angle = rect\n",
    "                        length = np.max([width,height])\n",
    "                        self.lengths.append(length)\n",
    "            return np.array(self.lengths)*self.nm_per_px\n",
    "            \n",
    "            \n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7fd9a010-e746-4a12-b97b-d3aa0ff5e933",
   "metadata": {},
   "source": [
    "# Cross-section\n",
    "\n",
    "**Note:** \n",
    "- nm_per_px (Calibration) should be the calibration for a 2048x2048 image, if the images are .dm3, the manual calibration is not needed.\n",
    "- If program runs slow, restart the kernel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "7333c652-c0c8-4490-bd32-ea2db1f8adfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\krist\\AppData\\Local\\Temp\\ipykernel_2220\\3299790051.py:112: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  self.checkpoint = torch.load(self.PATH, map_location=torch.device('cpu'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model Loaded\n",
      "Total interference time: 17.62s ; Time per Image: 17.619s\n"
     ]
    }
   ],
   "source": [
    "model = Prediction(cross = True)\n",
    "model.evaluate(nm_per_px = 0.069661) "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1c534da7-aca3-44f5-83a7-43e822721a0f",
   "metadata": {},
   "source": [
    "#### Use Check_Mask to adjust threshold, and erosion iterations\n",
    "\n",
    "**Note**\n",
    "- Default values should be good\n",
    "- Lowering erosion and mask threshold makes mask bigger\n",
    "- n : Index of image you want to check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "ba6ddc78-b1dc-4350-bb1d-e15d1ccdeb24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image checked: C:/Users/krist/Documents/masterRepo/data/train_cross/1-dm316h_jpg.rf.0d5872cc83a194e1e4214845e7aa92e9.jpg\n"
     ]
    }
   ],
   "source": [
    "n = 0\n",
    "\n",
    "Check_Mask(n, model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "e7311a78-c625-4a71-abaf-665fed0c90c5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mask threshold set to 0.90\n",
      "Calibration used: 0.1393 nm/px\n",
      "Average: 14.48nm, STDev: 9.46nm, Number counted: 11\n"
     ]
    }
   ],
   "source": [
    "area = model.statistics()\n",
    "\n",
    "print('Average: {0:.2f}nm, STDev: {1:.2f}nm, Number counted: {2:d}'.format(np.mean(area), np.std(area), len(area)))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c4a29a4f-bb31-4150-9c1d-e9be8e71e4e5",
   "metadata": {},
   "source": [
    "**Clear memory**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9a94aa1e-0a14-4c37-961c-800749e25f3d",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = None\n",
    "gc.collect()\n",
    "torch.cuda.empty_cache()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d5f7de4c-a814-4bea-8fab-ed2ecee3736a",
   "metadata": {},
   "source": [
    "# Length"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "f33c6b3e-8157-456f-8862-ee0c7902eff1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\krist\\AppData\\Local\\Temp\\ipykernel_2220\\3584532278.py:112: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.\n",
      "  self.checkpoint = torch.load(self.PATH, map_location=torch.device('cpu'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model Loaded\n",
      "Total interference time: 16.87s ; Time per Image: 16.871s\n"
     ]
    }
   ],
   "source": [
    "model = Prediction(cross = False)\n",
    "model.evaluate(nm_per_px = 0.20835) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "b389a605-4597-430a-80d8-6d9f6f44fb2e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n",
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n",
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n",
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n",
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n",
      "Image checked: C:/Users/krist/Documents/masterRepo/data/test_length/178_png.rf.53bb63769423ff90cb759a9bb85b5d47.jpg\n"
     ]
    }
   ],
   "source": [
    "n = 0\n",
    "Check_Mask(n,model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "341aeb21-2001-48f3-899f-565d951ff7d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mask threshold set to 0.50\n",
      "Calibration used: 0.4167 nm/px\n",
      "Average: 12.67nm, STDev: 3.20nm, Number counted: 3\n"
     ]
    }
   ],
   "source": [
    "l = model.statistics()\n",
    "print('Average: {0:.2f}nm, STDev: {1:.2f}nm, Number counted: {2:d}'.format(np.mean(l), np.std(l), len(l)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d87629f2-8ab6-4020-a86f-f2dbf5ac32ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = None\n",
    "gc.collect()\n",
    "torch.cuda.empty_cache()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
